apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supplier-order
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: supplier-order
    spec:
      containers:
      - name: ctse-supplier-orders
        image: maryamyumna/supplier-order:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m