name: Docker Build and Deploy

on:
  push:
    branches: 
      - main

env:
  DEPLOYMENT_NAME: supplier-order

jobs:

  setup-build-publish:

    name: Setup build and setup-build-publish
    runs-on: ubuntu-latest

    steps:
      - run: echo "Build started "
        uses: actions/checkout@v3
      - run: echo "Project repository has been clonded to runner(ubuntu)"

      #Login to Docker Hub
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}